core/urls.py
from django.conf.urls import patterns, include, url
from .views import *
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
                       url(r'^$', Home.as_view(), name='home'),
                       url(r'^user/', include('registration.backends.simple.urls')),
                       url(r'^user/', include('django.contrib.auth.urls')),
                       url(r'^post/create/$', login_required(PostCreateView.as_view()), name='post_create'),
                       url(r'^post/$', login_required(PostListView.as_view()), name='post_list'),
                       url(r'^post/(?P<pk>\d+)/$', login_required(PostDetailView.as_view()), name='post_detail'),
                       url(r'^post/update/(?P<pk>\d+)/$', login_required(PostUpdateView.as_view()), name='post_update'),
                       url(r'^post/delete/(?P<pk>\d+)/$', login_required(PostDeleteView.as_view()), name='post_delete'),
                       url(r'^post/(?P<pk>\d+)/comment/create/$', login_required(CommentCreateView.as_view()), name='comment_create'),
                       url(r'^post/(?P<post_pk>\d+)/comment/update/(?P<comment_pk>\d+)/$', login_required(CommentUpdateView.as_view()), name='comment_update'),
                       url(r'^post/(?P<post_pk>\d+)/comment/delete/(?P<comment_pk>\d+)/$', login_required(CommentDeleteView.as_view()), name='comment_delete'),
                       url(r'^vote/$', login_required(VoteFormView.as_view()), name='vote'),
                       url(r'^user/(?P<slug>\w+)/$', login_required(UserDetailView.as_view()), name='user_detail'),
                       url(r'^user/update/(?P<slug>\w+)/$', login_required(UserUpdateView.as_view()), name='user_update'),
                       url(r'^user/delete/(?P<slug>\w+)/$', login_required(UserDeleteView.as_view()), name='user_delete'),
                       url(r'^search/$', login_required(SearchPostListView.as_view()), name='search'),
                      )

final_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls')),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

CATEGORY_CHOICES = (
(0, 'Fiction'),
(1, 'Mystery & Crime'),
(2, 'Poetry'),
(3, 'Romance'),
(4, 'Science Fiction'),
(5, 'Thrillers'),
(6, 'Childrens'),
(7, 'Nonfiction'),
(8, 'Biography'),
)

RATING_CHOICES = (
(0, 'None'),
(1, '*'),
(2, '**'),
(3, '***'),
(4, '****'),
(5, '*****'),
)

class Post(models.Model):
  title = models.CharField(max_length=300)
  author = models.CharField(max_length=300)
  rating = models.IntegerField(choices=RATING_CHOICES, default=0)
  category = models.IntegerField(choices=CATEGORY_CHOICES, default=0)
  description = models.TextField(null=True, blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  user = models.ForeignKey(User)

  def __unicode__(self):
    return self.title

  def get_absolute_url(self):
    return reverse("post_detail", args=[self.id])

class Comment(models.Model):
  post = models.ForeignKey(Post)
  user = models.ForeignKey(User)
  created_at = models.DateTimeField(auto_now_add=True)
  text = models.TextField()

  def __unicode__(self):
    return self.text

class Vote(models.Model):
  user = models.ForeignKey(User)
  post = models.ForeignKey(Post, blank=True, null=True)
  comment = models.ForeignKey(Comment, blank=True, null=True)

  def __unicode__(self):
    return "%s upvoted" % (self.user.username)

templates/post/post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<p class="lead">Are you sure you want to delete"{{ post.title }}</p>
<form method="post" action="">
  {% csrf_token %}
  <button type="submit" class="btn btn-primary">Delete</button>
</form>
{% endblock %}

templates/post/post_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ post.title }}</h1>
<p>By {{ post.author }}</p>
{% if post.rating == 1 %}
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  ({{ post.rating }})
{% elif post.rating == 2 %}
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  ({{ post.rating }})
{% elif post.rating == 3 %}
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  ({{ post.rating }})
{% elif post.rating == 4 %}
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  ({{ post.rating }})
{% elif post.rating == 5 %}
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  <span class="glyphicon glyphicon-star"></span>
  ({{ post.rating }})
{% else %}
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  <span class="glyphicon glyphicon-star-empty"></span>
  ({{ post.rating }})
{% endif %}
{% if post.category == 0 %}
<p>Fiction</p>
{% elif post.category == 1 %}
<p>Mystery & Crime</p>
{% elif post.category == 2 %}
<p>Poetry</p>
{% elif post.category == 3 %}
<p>Romance</p>
{% elif post.category == 4 %}
<p>Science Fiction</p>
{% elif post.category == 5 %}
<p>Thrillers</p>
{% elif post.category == 6 %}
<p>Childrens</p>
{% elif post.category == 7 %}
<p>Nonfiction</p>
{% elif post.category == 8 %}
<p>Biography</p>
{% endif %}
<p>{{ post.description }}</p>
<p>Posted by <a href="{% url 'user_detail' slug=post.user.username %}">{{ post.user.username }}</a> on {{ post.created_at }}</p>
{% if post.user == user %}
<p><a href="{% url 'post_update' pk=post.id %}">Edit post</a></p>
<p><a href="{% url 'post_delete' pk=post.id %}">Delete post</a></p>
{% endif %}
{% if comments.count > 0 %}
<h3>{{ comments.count }} Comment{{ comments.count|pluralize }}:</h3>
{% endif %}
{% for comment in comments %}
<div class="panel">
  <p>{{ comment.text }}<p>
  {% if comment.user == user %}
  <p><a href="{% url 'comment_update' post_pk=post.id comment_pk=comment.id %}">Edit comment</a></p>
  <p><a href="{% url 'comment_delete' post_pk=post.id comment_pk=comment.id %}">Delete comment</a></p>
  {% endif %}
<p>Comment posted {% if comment.visibility == 0 %} by <a href="{% url 'user_detail' slug=comment.user.username %}">{{ comment.user.username }}</a> {% endif %} on {{ comment.created_at }}</p>
<form method="post" action="{% url 'vote' %}">
    <span class="badge">{{ comment.vote_set.all.count }} Vote{{ comment.vote_set.all.count|pluralize }}</span>
    {% csrf_token %}
    <input type="hidden" name="comment" value="{{ comment.id }}"/>
    <input type="hidden" name="post" value="{{ post.id }}"/>
    <input type="hidden" name="user" value="{{ user.id }}"/>
    {% if comment in user_votes %}
        <button class="btn btn-link">
          <span class="glyphicon glyphicon-thumbs-down"></span>
        </button>
    {% else %}
        <button class="btn btn-link">
          <span class="glyphicon glyphicon-thumbs-up"></span>
        </button>
    {% endif %}
</form>
</div>
{% endfor %}
<p><a href="{% url 'comment_create' pk=post.id %}">Write a response</a></p>
{% endblock %}

templates/post/post_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class="row">
<div class="col-lg-6">
<form method="post" action="">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
</div>
{% endblock %}

templates/post/post_list.html
{% extends 'base.html' %}
{% block content %}
{% for post in object_list %}
<div class="panel">
  <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
  <p>Posted by <a href="{% url 'user_detail' slug=post.user.username %}">{{ post.user.username }}</a> on {{ post.created_at }}</p>
  <form method="post" action="{% url 'vote' %}">
    <span class="badge">{{ post.comment_set.all.count }} Comment{{ post.comment_set.all.count|pluralize }}</span>
    <span class="badge">{{ post.vote_set.all.count }} Vote{{ post.vote_set.all.count|pluralize }}</span>
    {% csrf_token %}
    <input type="hidden" name="post" value="{{ post.id }}" />
    <input type="hidden" name="user" value="{{ user.id }}" />
    {% if post in user_votes %}
    <button class="btn btn-link">
      <span class="glyphicon glyphicon-thumbs-down"></span>
    </button>
    {% else %}
    <button class="btn btn-link">
      <span class="glyphicon glyphicon-thumbs-up"></span>
    </button>
    {% endif %}
  </form>
</div>
{% empty %}
<p>No results found.</p>
{% endfor %}
{% if is_paginated %}
<nav>
  <ul class="pager">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% endif %}
  </ul>
</nav>
{% endif %}
{% endblock %}